print("=== Resume Form ===")

name = input("Enter your name: ")
bio = input("Enter bio: ")
email = input("Enter email: ")
phone = input("Enter phone: ")
address = input("Enter address: ")
headline = input("Enter headline: ")
photo_url = input("Enter photo URL: ")
resume_url = input("Enter resume URL: ")

print("\n----- Resume -----")
print("Name:", name)
print("Bio:", bio)
print("Email:", email)
print("Phone:", phone)
print("Address:", address)
print("Headline:", headline)
print("Photo:", photo_url)
print("Resume:", resume_url)